LOCAL_PATH := $(call my-dir)

#GCamUrnyx
include $(CLEAR_VARS)
LOCAL_MODULE := UrnyxCam
LOCAL_SRC_FILES := app/UrnyxCam/UrnyxCam.apk
LOCAL_MODULE_CLASS := APPS
LOCAL_PRIVILEGED_MODULE := true
LOCAL_OVERRIDES_PACKAGES := Snap Camera2
LOCAL_CERTIFICATE := PRESIGNED
LOCAL_DEX_PREOPT := false
include $(BUILD_PREBUILT)
